name = "Nameless"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f62154267f76f6a3ca300365194a216942b8ec26f4402a6756a55e965086894c"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
